<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\BoletoProtest.Core\BoletoProtest.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.74.0.4162" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
